<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "website_provider"
 *
 * Auto generated by Extension Builder 2016-10-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Responsive Website',
	'description' => 'nnnnn-Template files and assets for this site. Always include static template at last!',
	'category' => 'distribution',
	'author' => 'Markus Dübbert',
	'author_email' => 'info@markusduebbert.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'dependencies' => 'cms,extbase,fluid',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);